### ISSUE TITLE
作者大大有个问题，popupwindow中使用背景色不生效

### ISSUE THREAD

**Issue by New-Zero-Zero** [F1ReKing/SignatureView#3]
第一次打开背景色的设置不生效，关闭窗口。打开第二次 背景色居然生效了。在studio中预览ui的时候，设置的背景色就是看不到的。

**Comment by F1ReKing** [comment]
> 第一次打开背景色的设置不生效，关闭窗口。打开第二次 背景色居然生效了。在studio中预览ui的时候，设置的背景色就是看不到的。

需要设置背景色属性值为16进制色值才会显示

**Comment by GeekBugs** [comment]
@869339820 需要设置背景色属性值为16进制色值才会显示

**Comment by New-Zero-Zero** [comment]
谢谢作者大大经过解惑已经弄明白
